// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_whatsapp from "./routes/admin/whatsapp.tsx";
import * as $api_name_ from "./routes/api/[name].ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_whatsapp_webhook from "./routes/api/whatsapp-webhook.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $websocket_wsBussiness from "./routes/websocket/wsBussiness.ts";
import * as $Counter from "./islands/Counter.tsx";
import * as $WhatsAppPanel from "./islands/WhatsAppPanel.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/whatsapp.tsx": $admin_whatsapp,
    "./routes/api/[name].ts": $api_name_,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/whatsapp-webhook.ts": $api_whatsapp_webhook,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/websocket/wsBussiness.ts": $websocket_wsBussiness,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/WhatsAppPanel.tsx": $WhatsAppPanel,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
